use_frameworks!

platform :ios, '14.0'

target 'nmbr_Example' do
  pod 'nmbr', :path => '../'
  pod 'icu4c-iosx', '71.1.2'

  pod 'SwiftLint'

  target 'nmbr_Tests' do
    inherit! :complete
  end
end
