use_frameworks!

platform :ios, '12.0'

target 'nmbr_Example' do
  pod 'nmbr', :path => '../'

  pod 'SwiftLint'

  target 'nmbr_Tests' do
    inherit! :complete
  end
end

post_install do |installer_representation|
  project = installer_representation.pods_project
  project.targets.each do |target|
    if target.name == "icu4c-iosx"
      target.build_configurations.each do |config|
        target.build_settings(config.name)['VALID_ARCHS'] = "$(ARCHS_STANDARD)"
      end
    end
  end
end
